name: Update CLI Formula

on:
  repository_dispatch:
    types: UpdateCliFormula

jobs:
  update_formula:
    env:
      version: ${{ github.event.client_payload.version }}
    name: Update CLI Formula to ${{env.version}}
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: updated formula
        env:
          urlPrefix: 'https://github.com/armory-io/armory-cli/releases/download/v${{env.version}}'
        run: echo ${{env.urlPrefix}}
        run: cp armory-cli_formula_template.txt ./Formula/armory-cli.rb
        run: perl -i -pe"s/#VERSION/$version/g" ./Formula/armory-cli.rb
        run: darwinAmd64Sha=$(curl -Ls $urlPrefix/armory-darwin-amd64 | shasum -a 256 | head -c 64)
        run: perl -i -pe"s/#darwin-amd64-sha/$darwinAmd64Sha/g" ./Formula/armory-cli.rb
        run: cat ./Formula/armory-cli.rb
      
